services:
  vscode:
    build:
      context: .
      args:
        # Make sure this GID is correct for your system
        DOCKER_GID: 988
    
    container_name: vscode_limited_env
    user: "1000"
    read_only: true
    tmpfs:
      - /tmp
      - /run

    volumes:
      # CORRECTED: Mount the HOST DIRECTORY where the image is mounted
      - /mnt/vscode_project:/home/coder/project:rw
      
      # Other volumes remain the same
      - /var/run/docker.sock:/var/run/docker.sock
      - vscode_data:/home/coder/.local
      - vscode_config:/home/coder/.config

    ports:
      - "8443:8080"
      
    environment:
      - PASSWORD=your_secure_password

    # NEW COMMAND: This fixes the permission error before starting the server.
    command: sh -c "sudo chown -R coder:coder /home/coder/.local /home/coder/.config && exec code-server --bind-addr 0.0.0.0:8080 /home/coder/project"

    restart: unless-stopped

volumes:
  vscode_data:
    driver: local
  vscode_config:
    driver: local