version: '3.8'

services:
  vscode:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      args:
        # IMPORTANT: Replace YOUR_DOCKER_GID with the GID from your host machine
        # Find it by running: getent group docker | cut -d: -f3
        DOCKER_GID: 988
    
    container_name: vscode_limited_env
    
    # Run as the 'coder' user defined in the Dockerfile (UID 1000)
    user: "1000"

    # Restricts container permissions for higher security
    # The root filesystem is read-only.
    read_only: true
    # But we make specific paths writable.
    tmpfs:
      - /tmp
      - /run

    volumes:
      # Mount the project directory with read-write access.
      # This is the ONLY persistent storage the user can write to.
      - ./project:/home/coder/project:rw
      
      # Mount the Docker socket to allow running docker commands from inside the container.
      - /var/run/docker.sock:/var/run/docker.sock
      
      # A named volume for code-server config and extensions
      - vscode_data:/home/coder/.local

    # Port mapping: <HOST_PORT>:<CONTAINER_PORT>
    ports:
      - "8443:8080"
      
    # Set a password for code-server. Change 'your_secure_password'
    environment:
      - PASSWORD=@myPasswd123

    # Set storage limit for the container's writable layer.
    # Note: This requires the 'overlay2' storage driver with 'projectquota' mount option enabled on the host's Docker daemon.
    # Check your /etc/docker/daemon.json. May not work on all systems.
    storage_opt:
      size: '2G' # Example: Limit container storage to 2GB

    # Restart policy
    restart: unless-stopped

volumes:
  vscode_data:
    driver: local